# Generated by Django 4.1.1 on 2024-10-19 21:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('viewer', '0014_alter_itemsonstock_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='role',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='media/avatars/profile_pic.png', null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='city',
            field=models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Povolena jsou pouze písmena.', regex='^[^\\W\\d_]+$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='communication_channel',
            field=models.CharField(choices=[('Pošta', 'Pošta'), ('Email', 'Email'), ('Telefon', 'Telefon')], default='Email', max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Povolena jsou pouze písmena.', regex='^[^\\W\\d_]+$'), django.core.validators.MinLengthValidator(2, message='Jméno musí mít alespoň 2 znaky.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, null=True, validators=[django.core.validators.RegexValidator(message='Povolena jsou pouze písmena.', regex='^[^\\W\\d_]+$'), django.core.validators.MinLengthValidator(2, message='Příjmení musí mít alespoň 2 znaky.')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=14, validators=[django.core.validators.RegexValidator(message='Nesprávný formát čísla.', regex='^\\+?\\d{9,}$')]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='zipcode',
            field=models.CharField(blank=True, max_length=5, validators=[django.core.validators.RegexValidator(code='invalid_zipcode', message='PSČ musí mít 5 číslic', regex='^\\d{5}$')]),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('television', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='viewer.television')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
