# Generated by Django 4.1.1 on 2024-10-20 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0015_remove_profile_role_alter_profile_avatar_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
