# Generated by Django 4.1.1 on 2024-10-20 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0016_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='viewer.order')),
                ('television', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.television')),
            ],
        ),
    ]
