# Generated by Django 4.1.1 on 2024-10-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/profile_pic.png', null=True, upload_to='avatars/'),
        ),
    ]
