# Generated by Django 4.1.1 on 2024-10-21 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_orderitem'),
        ('viewer', '0019_alter_profile_avatar'),
    ]

    operations = [
    ]
