# Generated by Django 4.1.1 on 2024-10-22 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0017_alter_profile_avatar'),
        ('viewer', '0020_merge_0017_orderitem_0019_alter_profile_avatar'),
    ]

    operations = [
    ]
