# Generated by Django 4.1.1 on 2024-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0021_merge_20241022_0927'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MobileOperationSystem',
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='construction',
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='display',
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='ram',
        ),
        migrations.RemoveField(
            model_name='mobilephone',
            name='user_memory',
        ),
        migrations.RemoveField(
            model_name='order',
            name='mobile_phone',
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='avatars/profile_pic.png', null=True, upload_to='avatars/'),
        ),
        migrations.DeleteModel(
            name='MobileConstruction',
        ),
        migrations.DeleteModel(
            name='MobileDisplay',
        ),
        migrations.DeleteModel(
            name='MobilePhone',
        ),
        migrations.DeleteModel(
            name='MobileRAM',
        ),
        migrations.DeleteModel(
            name='MobileUserMemory',
        ),
    ]
